import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

import ActionButton from "@/components/ActionButton";
import Badge from "@/components/common/Badge";
import type {
  CashflowSnapshotDetail,
  CashflowSourceNode,
} from "@/services/api/finance";
import { formatDecimalValue } from "@/features/finance/shared";

type SnapshotTreeNode = {
  id: string;
  name: string;
  depth: number;
  amount: number;
  autoGenerated: boolean;
  note: string | null;
  children: SnapshotTreeNode[];
};

interface CashflowSnapshotTreeProps {
  sources: CashflowSourceNode[];
  snapshot: CashflowSnapshotDetail;
}

function CashflowSnapshotTree({
  sources,
  snapshot,
}: CashflowSnapshotTreeProps) {
  const { t } = useTranslation();

  const treeNodes = useMemo(() => {
    const entryMap = new Map<
      string,
      CashflowSnapshotDetail["entries"][number]
    >();
    const primaryCurrency = snapshot.primary_currency;
    const rateMap = new Map<string, number>();
    snapshot.exchange_rates?.forEach((rate) => {
      const parsed = Number(rate.rate);
      if (!Number.isNaN(parsed)) {
        rateMap.set(rate.quote_currency, parsed);
      }
    });
    const usedEntryIds = new Set<string>();
    snapshot.entries.forEach((entry) => {
      entryMap.set(entry.source_id, entry);
    });

    const buildTree = (
      nodes: CashflowSourceNode[],
      depth: number,
    ): SnapshotTreeNode[] => {
      return nodes
        .map((node) => {
          const childNodes = buildTree(node.children ?? [], depth + 1);
          const entry = entryMap.get(node.id);
          let amountFromEntry = 0;
          if (entry) {
            const parsed = Number(entry.amount);
            if (Number.isFinite(parsed)) {
              const entryCurrency = entry.currency_code || primaryCurrency;
              if (entryCurrency !== primaryCurrency) {
                const rate = rateMap.get(entryCurrency);
                amountFromEntry = rate ? parsed * rate : 0;
              } else {
                amountFromEntry = parsed;
              }
            } else {
              amountFromEntry = 0;
            }
            usedEntryIds.add(node.id);
          }
          const childTotal = childNodes.reduce(
            (acc, child) => acc + child.amount,
            0,
          );
          const totalAmount =
            amountFromEntry !== 0 || childNodes.length
              ? amountFromEntry + childTotal
              : amountFromEntry;
          const includeNode =
            childNodes.length > 0 ||
            entry != null ||
            Math.abs(totalAmount) > 0.0000001;

          if (!includeNode) {
            return null;
          }

          return {
            id: node.id,
            name: node.name,
            depth,
            amount: childNodes.length
              ? childTotal + amountFromEntry
              : amountFromEntry,
            autoGenerated: entry?.is_auto_generated ?? false,
            note: entry?.note ?? null,
            children: childNodes,
          } satisfies SnapshotTreeNode;
        })
        .filter(Boolean) as SnapshotTreeNode[];
    };

    const builtTree = buildTree(sources, 0);

    const leftoverEntries: SnapshotTreeNode[] = [];
    snapshot.entries.forEach((entry) => {
      if (!usedEntryIds.has(entry.source_id)) {
        const parsed = Number(entry.amount);
        let resolved = Number.isFinite(parsed) ? parsed : 0;
        if (entry.currency_code && entry.currency_code !== primaryCurrency) {
          const rate = rateMap.get(entry.currency_code);
          resolved = rate ? resolved * rate : 0;
        }
        leftoverEntries.push({
          id: `${entry.source_id}-orphan`,
          name: entry.source_name,
          depth: 0,
          amount: resolved,
          autoGenerated: entry.is_auto_generated,
          note: entry.note,
          children: [],
        });
      }
    });

    return builtTree.concat(leftoverEntries);
  }, [
    snapshot.entries,
    snapshot.exchange_rates,
    snapshot.primary_currency,
    sources,
  ]);

  const [expanded, setExpanded] = useState<Set<string>>(() => new Set());
  const knownIdsRef = useRef<Set<string>>(new Set());

  useEffect(() => {
    const allNodeIds = new Set<string>();
    const nodesWithChildren = new Set<string>();

    const collect = (nodes: SnapshotTreeNode[]) => {
      nodes.forEach((node) => {
        allNodeIds.add(node.id);
        if (node.children.length) {
          nodesWithChildren.add(node.id);
          collect(node.children);
        }
      });
    };

    collect(treeNodes);

    setExpanded((prev) => {
      const next = new Set(prev);
      Array.from(next).forEach((id) => {
        if (!allNodeIds.has(id) || !nodesWithChildren.has(id)) {
          next.delete(id);
        }
      });
      nodesWithChildren.forEach((id) => {
        if (!knownIdsRef.current.has(id)) {
          next.add(id);
        }
      });
      return next;
    });

    knownIdsRef.current = allNodeIds;
  }, [treeNodes]);

  const toggleNode = useCallback((id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  const visibleNodes = useMemo(() => {
    const result: SnapshotTreeNode[] = [];
    const walk = (nodes: SnapshotTreeNode[]) => {
      nodes.forEach((node) => {
        result.push(node);
        if (node.children.length && expanded.has(node.id)) {
          walk(node.children);
        }
      });
    };
    walk(treeNodes);
    return result;
  }, [treeNodes, expanded]);

  if (!treeNodes.length) {
    return (
      <div className="rounded-lg border border-dashed border-base-200 bg-base-100 p-6 text-sm text-base-content/70">
        {t("finance.noCashflowEntries")}
      </div>
    );
  }

  const amountHeader = t("finance.cashflowAmountUnit", {
    currency: snapshot.primary_currency,
  });

  return (
    <div className="overflow-x-auto rounded-lg border border-base-200">
      <table className="table w-full">
        <thead className="bg-base-200/60 text-xs uppercase text-base-content/60">
          <tr>
            <th className="w-1/2">{t("finance.cashflowSource")}</th>
            <th className="w-32 text-right">{amountHeader}</th>
            <th className="min-w-[12rem]">{t("finance.cashflowNote")}</th>
          </tr>
        </thead>
        <tbody className="align-top text-sm text-base-content/80">
          {visibleNodes.map((node) => {
            const hasChildren = node.children.length > 0;
            const isExpanded = expanded.has(node.id);
            const indent = Math.min(node.depth, 6) * 1.5;
            const amountClass =
              node.amount > 0
                ? "text-success"
                : node.amount < 0
                  ? "text-error"
                  : "text-base-content";
            const formattedAmount =
              formatDecimalValue(node.amount) ?? node.amount.toString();
            const badges: string[] = [];
            if (node.autoGenerated) {
              badges.push(t("finance.autoGenerated"));
            }

            return (
              <tr key={node.id} className="border-base-200">
                <td className="align-top">
                  <div
                    className="flex items-start gap-2"
                    style={{ paddingLeft: `${indent}rem` }}
                  >
                    {hasChildren ? (
                      <ActionButton
                        label=""
                        iconName={isExpanded ? "chevron-down" : "chevron-right"}
                        iconOnly
                        size="xs"
                        variant="ghost"
                        color="neutral"
                        ariaLabel={
                          isExpanded ? t("common.collapse") : t("common.expand")
                        }
                        ariaExpanded={isExpanded}
                        onClick={() => toggleNode(node.id)}
                      />
                    ) : (
                      <span className="mt-1 inline-flex h-5 w-5 flex-shrink-0 items-center justify-center text-base-content/30">
                        •
                      </span>
                    )}
                    <div className="min-w-0 space-y-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="font-medium text-base-content">
                          {node.name}
                        </span>
                        {badges.map((badge) => (
                          <Badge
                            key={`${node.id}-${badge}`}
                            size="xs"
                            variant="outline"
                            className="font-normal"
                          >
                            {badge}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  </div>
                </td>
                <td className="w-32 align-top text-right">
                  <span className={`tabular-nums ${amountClass}`}>
                    {formattedAmount}
                  </span>
                </td>
                <td className="align-top">
                  {node.note ? (
                    <span className="block min-h-[2.25rem] text-sm text-base-content/80">
                      {node.note}
                    </span>
                  ) : (
                    <span className="text-base-content/40">—</span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

export default CashflowSnapshotTree;
