"""Task service facade with split query and mutation helpers."""

from __future__ import annotations

from lifeos_cli.db.services.task_effort import (
    recompute_subtree_totals,
    recompute_task_effort_after_timelog_change,
    recompute_task_self_minutes,
    recompute_totals_upwards,
)
from lifeos_cli.db.services.task_mutations import (
    TaskMoveResult,
    batch_delete_tasks,
    create_task,
    delete_task,
    move_task,
    reorder_tasks,
    update_task,
)
from lifeos_cli.db.services.task_queries import (
    TaskHierarchy,
    TaskStats,
    TaskView,
    TaskWithSubtasks,
    get_task,
    get_task_stats,
    get_task_with_subtasks,
    get_vision_task_hierarchy,
    list_tasks,
)
from lifeos_cli.db.services.task_support import (
    MAX_TASK_DEPTH,
    VALID_PLANNING_CYCLE_TYPES,
    VALID_TASK_STATUSES,
    CircularTaskReferenceError,
    InvalidPlanningCycleError,
    InvalidTaskDepthError,
    InvalidTaskOperationError,
    ParentTaskReferenceNotFoundError,
    TaskCannotBeCompletedError,
    TaskNotFoundError,
    VisionReferenceNotFoundError,
    ensure_vision_exists,
    load_task_subtree,
    validate_parent_task,
    validate_planning_cycle,
    validate_task_status,
    validate_task_status_change,
)

__all__ = [
    "MAX_TASK_DEPTH",
    "VALID_PLANNING_CYCLE_TYPES",
    "VALID_TASK_STATUSES",
    "CircularTaskReferenceError",
    "InvalidPlanningCycleError",
    "InvalidTaskDepthError",
    "InvalidTaskOperationError",
    "ParentTaskReferenceNotFoundError",
    "TaskCannotBeCompletedError",
    "TaskHierarchy",
    "TaskMoveResult",
    "TaskNotFoundError",
    "TaskStats",
    "TaskView",
    "TaskWithSubtasks",
    "VisionReferenceNotFoundError",
    "batch_delete_tasks",
    "create_task",
    "delete_task",
    "ensure_vision_exists",
    "get_task",
    "get_task_stats",
    "get_task_with_subtasks",
    "get_vision_task_hierarchy",
    "list_tasks",
    "load_task_subtree",
    "move_task",
    "recompute_subtree_totals",
    "recompute_task_effort_after_timelog_change",
    "recompute_task_self_minutes",
    "recompute_totals_upwards",
    "reorder_tasks",
    "update_task",
    "validate_parent_task",
    "validate_planning_cycle",
    "validate_task_status",
    "validate_task_status_change",
]
